### ISSUE TITLE
Add the request context and logger to all public methods in app/authorization.go

### ISSUE THREAD

**Issue by noxer** [mattermost/mattermost-server#21567]
#### Summary
To improve logging, we want to replace the global logger with a request specific one (which will add the request ID to the log message). The request context therefore contains a logger which is already pre-configured with the appropriate information. The task remains to pass the context to all methods used in fulfilling the request.

#### Tasks
- [ ] Change all public methods in `app/authorization.go` to receive `c request.CTX` as the first argument [1].
- [ ] Change all methods in `app/authorization.go` (even private ones) that use the `mlog` logger to use receive the context as well.
- [ ] Make sure all functions calling the changed methods pass along the context.
- [ ] Update the generated interfaces with `make generated`.
- [ ] Update the tests.

[1] Only if they have an `*App` receiver: `func (a *App) MethodName()`, others like `func (s *Server) ...` should be skipped. It they call a method you've changed, you should of course add the parameter as required.

#### Hints
- There changes tend to change a lot of files. Don't be afraid to ask for guidance when you feel it's getting out of control. Since a lot of these methods call each other it's common to have to change 10 or more files.
- Some methods already contain a `c *request.Context`. You can replace it with `c request.CTX`. `request.Context` implements the interface `request.CTX` so there should be no problem passing a `*Context` to a `CTX` parameter.
- Some methods may have references from the plugin API. Don't change the method signature there! The plugin API contains a preconfigured context for this purpose (`api.ctx`).
- The tests often work with a "TestHelper" (`th`) struct which contains a `th.Context`. If it's missing you can use a test helper from another package for ideas on how to add it.
- Most of the time you just need to regenerate the interface `AppIface`. `make app-layers` generates just this one interface and is generally faster than `make generated`.
- `api4` has it's own, separate context struct. That context contains the `request.CTX` we need. You can use `c.AppContext` to pass it to `App` methods.

**Comment by Soj447** [comment]
I would like to take this.

**Comment by rubiagatra** [comment]
Let me try

**Comment by hanzei** [comment]
Awesome, thanks @rubiagatra :+1:

**Comment by hanzei** [comment]
@rubiagatra Do you have any questions regarding the ticket?

**Comment by sahildotexe** [comment]
Can I give this a try if the issue is still open?

**Comment by hanzei** [comment]
Sure, please do @sahildotexe

**Comment by hanzei** [comment]
Making the ticket available again

**Comment by srisri332** [comment]
@hanzei , I would like to work on this issue.

**Comment by srisri332** [comment]
Hey @amyblais , I have couple of doubts that I need some clarification for. Can you please let me know whom I can contact for these?

**Comment by amyblais** [comment]
@srisri332 Feel free to post any questions in our https://community.mattermost.com/core/channels/tickets channels.

**Comment by hanzei** [comment]
Closing as won't do
